### ISSUE TITLE
Empty lists always returned from session.run

### ISSUE THREAD

**Issue by ljwagerfield** [eaplatanios/tensorflow_scala#159]
I'm receiving the following output:

```
[info] Running Application 
List()
List()
```

From the following application:
```scala
import org.platanios.tensorflow.api.core.Shape
import org.platanios.tensorflow.api.core.client.Session
import org.platanios.tensorflow.api._

object Application extends App {
  val constant = tf.constant[Float](Tensor.ones(Shape(10, 1)))
  val variable = tf.variable[Float]("weights", Shape(10, 1), tf.ZerosInitializer)
  val init     = tf.globalVariablesInitializer()

  using(Session()) { session =>
    session.run(targets = Set(init))
    println(
      session.run(targets = Set(constant))
    )
    println(
      session.run(targets = Set(variable.value))
    )
  }
}
```

I'm using `"org.platanios" %% "tensorflow" % "0.4.2-SNAPSHOT" classifier "darwin-cpu-x86_64"`

---

I expect the output to be a matrix of `1`s followed by a matrix of `0`s.

Am I missing something?

**Comment by DirkToewe** [comment]
There are fetches and there are targets. Targets are executed, but their value is not returned. Targets are usually used to just change the state of the Session (e.g. change/increment the value of a variable).

Fetches on the other hand are computed and then the computed result is returned. Simply replacing the `targets = ` with `fetches = ` should work.

**Comment by ljwagerfield** [comment]
Interesting!

Is a fetch a superset of a target?

I.e. can I put a `init` in the `fetch` set, and have everything continue to work the same?

**Comment by DirkToewe** [comment]
I believe You cannot, but You can have both `feeds` and `fetches` in the same `session.run`. But be careful You should not initialize and read a variable in the same `session.run` call. Tensorflow executes operations in parallel and arbitrary order (unless order of execution is enforced by control- and/or data-flow dependencies).

You can also enforce that some operation is executed before another one by introducting [control dependencies](https://www.tensorflow.org/api_docs/python/tf/control_dependencies):
```scala
val x = tf.variable[Float]( "x", Shape(), initializer = RandomNormalInitializer(-10,+10) )
val init = tf.globalVariablesInitializer()
val init_and_read = tf.createWith( controlDependencies = Set(init) ){
  x.value
}

val sess = Session()
try {
  val Seq(val0: Tensor[Float]) = sess.run( fetches=Seq(init_and_read) )
  val Seq(val1: Tensor[Float]) = sess.run( fetches=Seq(init_and_read) )
  println( val0.summarize() )
  println( val1.summarize() )
}
finally {
  sess.close()
}
```
`init_and_read` waits until `init` has executed before reading the value of `x`.

**Comment by ljwagerfield** [comment]
If I change `targets` to `fetches` in my above code sample, I get the following unresolved implicit:
```
could not find implicit value for evidence parameter of type org.platanios.tensorflow.api.implicits.helpers.OutputStructure[scala.collection.immutable.Set[org.platanios.tensorflow.api.ops.Output[Float]]]
```

What's the correct way of "fetching" the constant and variable in my above example? Am I just missing some imports?

**Comment by eaplatanios** [comment]
@ljwagerfield `Set`s are not "fetchable" because the order of the items in the set is not fixed. If you change your `Set` to a `Seq` it should work fine. Also, I don't believe `Op`s are fetchable either (because they don't have a value that they return) and so you shouldn't put an `init` in `fetches`. You can always provide both `fetches` and `targets` based on what you want computed and executed, respectively.

**Comment by ljwagerfield** [comment]
Is the distinction between what is fetchable and what isn't a TensorFlow thing, or is this a paradigm that's introduced by TensorFlow Scala?

I ask because in the Python library, they don't seem to distinguish (you put everything into run).

That's not to question any design choices: I'm just hoping to further my understanding of TensorFlow and of this library 😄

**Comment by DirkToewe** [comment]
It's at least a "low-level" Tensorflow thing. The [C++ API](https://www.tensorflow.org/api_docs/cc/class/tensorflow/client-session.html#classtensorflow_1_1_client_session_1a706a9b3dfde4aa64c7ca9e85ac666b1d), for example, also distinguishes between `fetch_outputs` and `run_outputs`. It may just be a performance thing because for a fetch, data has to be copied.

In Scala there is another reason for the dichotomy: The type system. The operations in TF4S are generically typed (Output[Float], Output[Boolean], ...) and the return types (Tensor[Float], Tensor[Boolean], ...) are computed accordingly. For initialization operations, that return type would be something like `Tensor[Unit]` and that would not make much sense.

**Comment by ljwagerfield** [comment]
Thank you :+1:

**Comment by eaplatanios** [comment]
Thanks for providing an explanation @DirkToewe ! That's accurate. Note also that it's not just a performance thing but also semantics-related. It does not make sense to "fetch" an op, as it does not contain any data. It's just something that's executed for its side effects.
