### ISSUE TITLE
Native jni libs contain only darwin artifacts

### ISSUE THREAD

**Issue by mandar2812** [eaplatanios/tensorflow_scala#188]
When I import tf scala 0.5.4 in my DynaML build, it fails to load the JNI library. After inspecting the jar file I found that it contains bindings only for Mac, but not for Linux or windows. I have built my code on an Ubuntu PC

```
❯ jar -tf ./target/universal/stage/lib/org.platanios.tensorflow-jni_2.12-0.5.4.jar | grep "lib"
native/darwin-x86_64/libtensorflow_jni.so
native/darwin-x86_64/libtensorflow_ops.so

```

**Comment by eaplatanios** [comment]
Thanks @mandar2812 ! I've messed up this release because of how I tried adding support for windows. Could you please try again using `0.5.5`?

**Comment by steve-gailey-exa** [comment]
Sure will do and thanks for your work on this project - I for one really appreciate it. Do you have a funding page?

S.

[X]
Steve Gailey | Solutions Architecture
steve.gailey@exabeam.com<mailto:steve.gailey@exabeam.com> | +44 7795 220392
exabeam.com<https://www.exabeam.com/> | facebook<https://www.facebook.com/exabeam/> | linkedin<https://www.linkedin.com/company/exabeam> | twitter<https://twitter.com/exabeam>







[X]<https://www.gartner.com/reviews/market/security-information-event-management/vendor/Exabeam/?pid=27389%20target=_blank%20rel=noopener>


On 24 Sep 2020, at 19:09, Anthony Platanios <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks for letting me know @mandar2812<https://github.com/mandar2812> ! I've messed up this release because of how I tried adding support for windows. Could you please try again using 0.5.5?

**Comment by mandar2812** [comment]
@eaplatanios It works now! Thanks for looking into this.
