### ISSUE TITLE
CUDA 9.1 support.

### ISSUE THREAD

**Issue by strelec** [eaplatanios/tensorflow_scala#93]
Cuda 9.1 has been out for a few months now.

/lib64/libcublas.so.9.0: version `libcublas.so.9.0' not found

Could we depend just on /lib64/libcublas.so.9, that is, without the minor number, to be future-proof?

**Comment by eaplatanios** [comment]
For this I’ve followed the same approach that the Python API follows and released precompiled binaries for CUDA 9. Are there no API changes between 9 and 9.1? If there aren’t any, then why does the official TensorFlow API also release for 9 only? I’m just wondering because I’m not familiar and don’t want to risk it. Otherwise, your suggestion totally makes sense and I’d be willing to make the change.

Actually, the current precompiled binaries I package are the ones provided with the main TensorFlow Python API and so are identical. I’m not compiling them from scratch in the current release.

**Comment by eaplatanios** [comment]
@strelec I'll close this given that I'm just using the official pre-compiled binaries now. Please let me know if you have an idea for how to more easily support multiple versions of CUDA. I don't really know what compatibility guarantees CUDA minor versions provide so I'm not sure if the original solution you propose would work. Feel free to comment if you have more information. :)
